
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
// import Head from 'next/head';
// import {  NextUIProvider } from '@nextui-org/react';
import { ReactQueryClientProvider } from "@/services/provider";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const noLayoutRoutes = ['/signin', '/signup'];

  return (
    <html lang="en">
      <head>
        <link href="https://fonts.googleapis.com/css2?family=Kumbh+Sans:wght@500&display=swap" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet"/>
        <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;400;700&display=swap" rel="stylesheet" />

      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
     <ReactQueryClientProvider>
        {/* <NextUIProvider> */}
       
          {children}
        {/* </NextUIProvider> */}
        <ToastContainer />
        </ReactQueryClientProvider>
       
      </body>

    </html>
  );
}
